---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Use kubectl to delete the www-nginx service
      shell: kubectl delete -f www-nginx.yml
      args:
        chdir: $HOME
        removes: www-nginx.txt

    - name: Delete the www-nginx lock file
      file:
        path: $HOME/www-nginx.txt
        state: absent

    - name: Use kubectl to delete www-apache services
      shell: kubectl delete -f www-apache.yml
      args:
        chdir: $HOME
        removes: www-apache.txt

    - name: Delete the www-apache lock file
      file:
        path: $HOME/www-apache.txt
        state: absent

    - name: Use kubectl to delete the flask services
      shell: kubectl delete -f openai.yml
      args:
        chdir: $HOME
        removes: openai.txt

    - name: Delete the flask lock file
      file:
        path: $HOME/openai.txt
        state: absent

    - name: Use kubectl to delete services bookinfo-gateway
      shell: kubectl delete -f bookinfo-gateway.yaml
      args:
        chdir: $HOME
        removes: bookinfo-gateway.txt

    - name: Delete the lock file
      file:
        path: $HOME/bookinfo-gateway.txt
        state: absent

    - name: Use kubectl to delete services bookinfo
      shell: kubectl delete -f bookinfo.yaml
      args:
        chdir: $HOME
        removes: bookinfo.txt

    - name: Delete the lock file
      file:
        path: $HOME/bookinfo.txt
        state: absent

    - name: Use helm to delete external-dns
      shell: helm uninstall external-dns 
      args:
        chdir: $HOME
        removes: external-dns.txt

    - name: Delete the lock file
      file:
        path: $HOME/external-dns.txt
        state: absent
