---
- hosts: controller.do.iot4.net
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the leza template
      copy:
        src: leza.yml
        dest: $HOME/leza.yml

    - name: Use kubectl to deploy the leza service
      shell: kubectl apply -f leza.yml >> leza.txt
      args:
        chdir: $HOME
        creates: leza.txt
