---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the www-nginx template 
      copy:
        src: www-nginx.yml
        dest: $HOME/www-nginx.yml

    - name: Use kubectl to deploy the www service
      shell: kubectl apply -f www-nginx.yml
      args:
        chdir: $HOME
        creates: www-nginx.txt 

    - name: Copy the www-apache template 
      copy:
        src: www-apache.yml
        dest: $HOME/www-apache.yml

    - name: Use kubectl to deploy the www service
      shell: kubectl apply -f www-apache.yml
      args:
        chdir: $HOME
        creates: www-apache.txt 
