- name: Build the lamp stack 
  become: true
  hosts: all
  roles:
  pre_tasks: 
  - name: Mount the nfs file system
    become: yes
    mount:
      name: /mnt
      fstype: nfs4
      opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
      src: '{{efs_target}}:/'
      state: mounted
  - name: Enable a LAMP Stack
    shell: amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
  - name: Install yum dependencies
    yum:
      name: [httpd, php-mbstring, python-pip, python-wheel]
      update_cache: yes
      state: present
  - name: Sync the S3 tartet to /mnt
    shell: "aws s3 sync {{ s3_target }} /mnt"
  - name: "Stat the {{ html_root }} to see if its dir or link"
    stat:
        path: "{{ html_root }}"
    register: sym

  - name: "Delete the directory if dir"
    file:
        path: "{{html_root}}"
        state: absent
    when: sym.stat.isdir is defined and sym.stat.isdir 

  - name: Symlink html_root to /mnt
    file:
        dest: "{{ html_root }}"
        src: "/mnt"
        state: link
    when: sym.stat.islink is not defined or syml.stat.islink == False

  - name: Enable the httpd service
    service:
      name: httpd
      state: started
      enabled: true

