# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
      ## Scans too many files for one commit. Be careful when enabling
      ## Requires python >=3.10
      # Be careful when enabling
      #-   repo: https://github.com/ansible-community/ansible-lint
      #rev: v24.2.1
      #hooks:
      #- id: ansible-lint
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_fmt
        #- id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_docs_replace
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        name: Check YAML
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
    -   id: check-json
    -   id: pretty-format-json
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: requirements-txt-fixer
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
