---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-newrelic
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - flask-newrelic.apps.viharc.com
     secretName: flask-new-relic-cert
  rules:
  - host: "flask-newrelic.apps.viharc.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: flask-newrelic
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-newrelic
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-newrelic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-newrelic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-newrelic
  template:
    metadata:
      labels:
        app: flask-newrelic
    spec:
      containers:
      - name: openai
        image: vchokshi/openai:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openaiapikey
                key: access-token
                optional: false
          - name: NEWRELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelicapikey
                key: access-token
                optional: false
          - name: FLASK_APP
            value: "app"
          - name: FLASK_ENV
            value: "production"
          - name: OTEL_EXPORTER_OTLP_HEADERS
            value: "api-key=$(NEWRELIC_LICENSE_KEY)"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "https://otlp.nr-data.net:4317"
          - name: OTEL_SERVICE_NAME
            value: "flask-newrelic"
