---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  tasks:
    - name: Use kubectl to destroy services
      shell: "kubectl delete -f {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - beats.yml
        - black.yml
        - dvwa.yml
        - leza.yml
        - fo.yml
        - mutillidae.yml
        - webgoat.yml
        - viharc.yml
        - flask-honeycomb.yml
        - flask-newrelic.yml
        - vpn.yml
        - keycloak.yaml
        - elk.yml
        - https://download.elastic.co/downloads/eck/2.9.0/operator.yaml
        - beats.yml
      ignore_errors: true

    - name: Use kubectl to delete pvc
      shell: "kubectl delete pvc {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - elastic-*
      ignore_errors: true

    - name: Unintall istio
      shell: bin/istioctl uninstall --purge -y
      args:
        chdir: $HOME/istio-1.20.0
      ignore_errors: true

    - name: Pause for 30 seconds before taking more things down
      ansible.builtin.pause:
        seconds: 30

    - name: Use helm to destroy kubeview
      shell: "helm uninstall {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - kubeview
        - wordpress
      ignore_errors: true

    - name: Pause for 30 seconds before taking down DNS
      ansible.builtin.pause:
        seconds: 30

    - name: Use helm to destroy DNS & Ingress
      shell: "helm uninstall {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - external-dns
        - ingress-nginx
      ignore_errors: true
