
- name: Install New Relic infrastructure and logs
  hosts: all
  roles:
  - role: newrelic.newrelic_install
  vars:
    targets:
      - infrastructure
      - logs
  environment:
    NEW_RELIC_API_KEY: "{{ lookup('env', 'NEWRELIC_API_KEY') }}"
    NEW_RELIC_ACCOUNT_ID: "{{ lookup('env', 'NEWRELIC_ACCOUNT_NUMBER') }}"
    NEW_RELIC_REGION: US
