- name: Update /etc/sysctl.conf to enable ipv4 forwarding
  become: yes
  replace: dest=/etc/sysctl.conf regexp='^#net\.ipv4\.ip_forward=1$' replace='net.ipv4.ip_forward=1'

- name: Update sysctl
  become: yes
  shell: 'sysctl -p'

- name: Issue the Iptables command for MASQUERADE
  become: yes
  shell: 'iptables -t nat -A POSTROUTING -o eth0 -s {{subnet_range}} -j MASQUERADE'
