---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webgoat
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - goat.labs.iot4.net
     secretName: webgoat-cert
  rules:
  - host: "goat.labs.iot4.net"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webgoat
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: webgoat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
spec:
  selector:
    matchLabels:
      app: webgoat
  replicas: 1
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: webgoat/webgoat-8.0
        ports:
        - containerPort: 8080
