---
- name: Download Kubeview
  unarchive:
    src: https://github.com/benc-uk/kubeview/releases/download/0.1.31/kubeview-0.1.31.tgz
    dest: $HOME
    remote_src: true

- name: Copy our values file over
  copy:
    src: kubeview-values.yml
    dest: $HOME/kubeview/values.yml

- name: Install Kubeview
  shell: helm upgrade --install kubeview ./kubeview/ -f kubeview/values.yml
  args:
    chdir: $HOME
