---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  tasks:
    - name: Copy the atlantis manifest over
      copy:
        src: atlantis.yml
        dest: $HOME/atlantis.yml
    - name: Use kubectl to deploy atlantis
      shell: kubectl apply -f atlantis.yml >> atlantis.txt
      args:
        chdir: $HOME
        creates: atlantis.txt
