---
- hosts: controller.do.iot4.net
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the hello kubernetes template
      copy:
        src: hello-kubernetes.yml
        dest: $HOME/

    - name: Use kubectl to deploy the hello-kubernetes service
      shell: kubectl apply -f hello-kubernetes.yml >> hello-kubernetes.txt
      args:
        chdir: $HOME
        creates: hello-kubernetes.txt
