---
- hosts: control_plane
  become: yes
  become_user: ubuntu
  tasks:
    - name: Use kubectl to destroy services
      shell: "kubectl delete -f {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - black.yml
        - vpn.yml
        - gravity.yml
        - bookinfo-gateway.yaml
      ignore_errors: true

    - name: Use helm to destroy wordpress
      shell: "helm uninstall {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - wordpress
      ignore_errors: true

    - name: Unintall istio
      shell: bin/istioctl uninstall --purge -y
      args:
        chdir: $HOME/istio-1.20.0
      ignore_errors: true

    - name: Use helm to destroy Ingress
      shell: "helm uninstall {{ item }}"
      args:
        chdir: $HOME
      with_items:
        - ingress-nginx -n ingress-nginx
      ignore_errors: true
