---
#- name: Impoart and build the botnet
  #ansible.builtin.import_playbook: bot.yml

- name: Import and execute the Prequesitues playbook
  ansible.builtin.import_playbook: prereqs.yml

- name: Import and execute kubernetes playbook
  ansible.builtin.import_playbook: kubernetes.yml

- name: Install helm as a package manager for k8s
  ansible.builtin.import_playbook: helm.yml

- name: Import and execute the cert-manager
  ansible.builtin.import_playbook: cert-manager.yml

- name: Import and execute the secrets playbook
  ansible.builtin.import_playbook: secrets.yml

- name: Import and execute the ingress controller playbook
  ansible.builtin.import_playbook: ingress.yml

- name: Import and execute the istio playbook
  ansible.builtin.import_playbook: istio.yml

- name: Use helm to install externaldns
  ansible.builtin.import_playbook: externaldns.yml

- name: Import and execute the doccm playbook
  ansible.builtin.import_playbook: do_ccm.yml

- name: Import and execute the docsi playbook
  ansible.builtin.import_playbook: do_csi.yml

- name: Import and execute the playbook for new relic
  ansible.builtin.import_playbook: new_relic.yml

- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  roles:
    - kubeview
    - elk
    - keycloak
    - bookstore
    #- hello-kubernetes
    #- vpn
    #- wordpress
    #- dvwa
    #- mutillidae
    #- leza
    #- fo
    #- webgoat
    #- flask
    #- viharc
    #- black
