---
- name: Impoart and build the botnet
  ansible.builtin.import_playbook: init.yml

- hosts: control_plane
  become: yes
  become_user: ubuntu
  gather_facts: false
  roles:
    - dashboard
    - kubeview
    - vpn
    - black
    - gravity
    - splunk
    - elk
    - keycloak
    - bookstore
    - hello-kubernetes
    - wordpress
    - dvwa
    - mutillidae
    #- leza
    #- fo
    #- webgoat
    #- flask
    - viharc
