---
- hosts: do
  become: yes
  tasks:
    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present
      retries: 5
      delay: 5
      register: result
      until: "result is not failed"

    - name: install packages
      become: yes
      package:
        name:
          - tar
          - unzip
          - gzip
          - scanlogd
          - golang-go
        state: present
      when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')
      retries: 5
      delay: 10
      register: result
      until: "result is not failed"
