- name: Install nfs services on Debian
  become: yes
  apt:
    name: nfs-common
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install nfs services on RedHat
  become: yes
  yum:
    name: nfs-utils
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
