apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: splunk
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - splunk.labs.iot4.net
     secretName: splunk-cert
  rules:
  - host: "splunk.labs.iot4.net"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: splunk
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: splunk
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: splunk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
spec:
  selector:
    matchLabels:
      app: splunk
  replicas: 1
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - name: splunk
        image: splunk/splunk:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: SPLUNK_START_ARGS
            value: "--accept-license"
          - name: SPLUNK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vp
                key: pass
                optional: false
