download:
	curl -Ss -L https://cdn-scripts.signifyd.com/api/company_toolkit.js > company_toolkit.js
	curl -Ss -L https://cdn-scripts.signifyd.com/api/script-tag.js > script-tag.js
	curl -Ss -L https://s3-us-west-2.amazonaws.com/jsstore/a/5N0H80M/ge.js > ge.js
	md5sum *.js > checksums.txt
	sha256sum *.js >> checksums.txt
