---
- hosts: controller
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the bookinfo and bookinfo gateway charts to the controller
      copy:
        src: "{{ item }}"
        dest: $HOME
      with_items:
        - bookinfo.yaml
        - bookinfo-gateway.yaml

    - name: Deploy the bookinfo app
      shell: kubectl apply -f bookinfo.yaml >> bookinfo.txt
      args:
        chdir: $HOME
        creates: bookinfo.txt

    - name: Associate the bookinfo app with an Istio Gateway
      shell: kubectl apply -f bookinfo-gateway.yaml >> bookinfo-gateway.txt
      args:
        chdir: $HOME
        creates: bookinfo-gateway.txt
