---
- hosts: do
  become: yes
  tasks:
    - name: create Docker config directory
      file: path=/etc/docker state=directory

    - name: changing Docker to systemd driver
      copy:
       dest: "/etc/docker/daemon.json"
       content: |
         {
         "exec-opts": ["native.cgroupdriver=systemd"]
         }

    - name: install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
      retries: 5
      delay: 10
      register: result
      until: "result is not failed"
