---
- hosts: controller
  become: yes
  become_user: ubuntu
  gather_facts: false
  tasks:
    - name: Copy the DOCSI files over
      copy:
        src: "{{ item }}"
        dest: "$HOME/{{item}}"
      tags:
        - build
      with_items:
        - crds.yaml
        - driver.yaml
        - pvc.yml
        - pod.yml

    - name: Use kubectl to deploy DOCSI CRDs
      shell: kubectl apply -f crds.yaml
      args:
        chdir: $HOME
        creates: crds.txt

    - name: Use kubectl to deploy DOCSI
      shell: kubectl apply -f driver.yaml
      args:
        chdir: $HOME
        creates: docsi.txt
