---
- hosts: controller.do.iot4.net
  become: yes
  tasks:
    - name: Set hostname of box
      hostname:
        name: "bot-controller"

- hosts: worker-0.do.iot4.net
  become: yes
  tasks:
    - name: Set hostname of box
      hostname:
        name: "bot-worker-0"

- hosts: worker-1.do.iot4.net
  become: yes
  tasks:
    - name: Set hostname of box
      hostname:
        name: "bot-worker-1"


- hosts: worker-2.do.iot4.net
  become: yes
  tasks:
    - name: Set hostname of box
      hostname:
        name: "bot-worker-2"


- hosts: worker-3.do.iot4.net
  become: yes
  tasks:
    - name: Set hostname of box
      hostname:
        name: "bot-worker-3"
- hosts: all
  become: yes
  tasks:
    - name: Set hostname of box
      hostname:
        name: "{{ ansible_host  }}"
    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present
      retries: 5
      delay: 5
      register: result
      until: "result is not failed"

    - name: install packages
      become: yes
      package:
        name:
          - tar
          - unzip
          - gzip
          - scanlogd
          - golang-go
        state: present
      when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')
      retries: 5
      delay: 10
      register: result
      until: "result is not failed"

- hosts: aws
  become: yes
  tasks:
    - name: Add gpg using apt
      apt:
        name: gnupg
        update_cache: yes
        state: present
