---
  - name: Check to see if wp-cli is installed
    stat:
      path: /usr/local/bin/wp
    register: wp

  - name: Install & Conifigure wp-cli
    # become: yes
    block:
      - name: Get wp-cli from https
        get_url:
          url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          dest: /tmp
          mode: 0755
      - name: Move wp-cli.phar to /usr/local/bin/wp
        command: mv /tmp/wp-cli.phar /usr/local/bin/wp
    when: wp.stat.exists == false
