name: Check for prohibited files

on:
  push:
    branches:
      - master
jobs:
  prohibit_files:
    name: Check for prohibited files
    runs-on: ubuntu-latest
    steps:
      - name: Check for prohibited files
        run: ./.github/workflows/prohibit_files.sh
        shell: sh
